import { randomUUID } from "node:crypto";
import { beforeAll, beforeEach, afterAll, describe, expect, it, vi } from "vitest";
import { PGlite } from "@electric-sql/pglite";
import Fastify from "fastify";
import { applyVersionedMigrations } from "../../../packages/database/src/versionedMigrate.js";
import { ManagementStore, employeeInput, glossaryInput, type DatabaseConnection, type SessionSnapshot } from "../../../packages/database/src/managementStore.js";
import { registerManagementRoutes } from "./managementRoutes.js";
import { createSession,verifySession } from "../../dashboard/lib/session.js";
const actor = { role:"ADMIN" as const,name:"shared-admin" },env = { NUNES_ADMIN_PASSWORD:"offline-admin",NUNES_VIEWER_PASSWORD:"offline-viewer",AUTH_SECRET:"offline-signing-secret-that-is-long-enough",DATABASE_URL:"configured-only",PLIVO_AUTH_TOKEN:"private-token",PLIVO_AUTH_ID:"private-id",PLIVO_NUMBER:"+919876543210",SARVAM_API_KEY:"private-sarvam" };
const employee = { name:"Test Employee",phone:"+91 (98765) 43210",department:"Calibration",defaultLanguage:"ta",enabled:true,callingRole:"staff",availability:"available" };
const glossary = { sourceTerm:"Fluke 754",preferredTranslation:"",languageFrom:"en",languageTo:"ta",category:"MODEL",preserveExact:true,enabled:true };
let pg: PGlite,db:DatabaseConnection,store:ManagementStore;
function connection(engine: Pick<PGlite,"query" | "exec"> & { transaction?: (callback: (tx: any) => Promise<any>) => Promise<any> }): DatabaseConnection {
  const result: DatabaseConnection = {
    query: async <T>(text:string,args:unknown[] = []) => args.length ? (await engine.query<T>(text,args)).rows : (await engine.exec(text)).flatMap(item=>item.rows) as T[],
    transaction: operation => typeof engine.transaction === "function" ? engine.transaction(tx => operation(connection(tx))) : operation(result),
  };return result;
}
function snapshot(id:string, prefix = randomUUID()):SessionSnapshot { return { sessionId:id,state:"connected",providerMode:"offline",customer:{requestUuid:`${prefix}-customer-request`,callUuid:`${prefix}-customer-call`,streamId:`${prefix}-customer-stream`,answered:true,socketConnected:true},staff:{requestUuid:`${prefix}-staff-request`,callUuid:`${prefix}-staff-call`,streamId:`${prefix}-staff-stream`,answered:true,socketConnected:true},offlineTranslation:{queued:{customerToStaff:0,staffToCustomer:0},metrics:{lastError:"",prepared:1,overflow:0,timings:[]}} }; }
async function appFor(customStore = store) { const app=Fastify();await registerManagementRoutes(app,{store:customStore,env});await app.ready();return app; }
beforeAll(async()=>{pg=new PGlite();db=connection(pg);store=new ManagementStore(db);await applyVersionedMigrations(db);},30000);
beforeEach(async()=>{await pg.exec("TRUNCATE employees,call_sessions,translation_glossary,audit_logs CASCADE");await pg.query("UPDATE system_settings SET setting_value=$1::jsonb WHERE setting_key='retention'",[JSON.stringify({callDays:30,auditDays:90,retainAudio:false,retainTranscripts:false})]);});
afterAll(async()=>{await pg.close();});
describe("Phase 4 embedded PostgreSQL migrations",()=>{
  it("applies versioned schema, ledger and indexes; reruns without changes",async()=>{expect(await applyVersionedMigrations(db)).toEqual([]);expect((await db.query("SELECT version FROM schema_migrations")).length).toBe(2);await store.health();expect((await db.query("SELECT indexname FROM pg_indexes WHERE indexname='call_event_idempotency'")).length).toBe(1);});
  it("rejects changed migration checksum",async()=>{await db.query("UPDATE schema_migrations SET checksum=$1 WHERE version='0002_phase4_management.sql'",["0".repeat(64)]);await expect(applyVersionedMigrations(db)).rejects.toThrow("CHECKSUM");await db.query("DELETE FROM schema_migrations WHERE version='0002_phase4_management.sql'");const {createHash}=await import("node:crypto");const {readFile}=await import("node:fs/promises");const source=await readFile(new URL("../../../packages/database/migrations/0002_phase4_management.sql",import.meta.url),"utf8");await db.query("INSERT INTO schema_migrations(version,checksum) VALUES($1,$2)",["0002_phase4_management.sql",createHash("sha256").update(source).digest("hex")]);});
  it("enforces database safety constraints",async()=>{const id=randomUUID();await store.beginSession(id,"+919876543210");await expect(db.query("UPDATE call_sessions SET audio_isolation_verified=true WHERE id=$1",[id])).rejects.toThrow();await expect(db.query("UPDATE call_sessions SET production_translation_authorized=true WHERE id=$1",[id])).rejects.toThrow();});
  it("enforces relational integrity and global ownership",async()=>{const id=randomUUID(),other=randomUUID(),first=snapshot(id);await store.beginSession(id,"+919876543210");await store.snapshot(first);await store.beginSession(other,"+919876543210");await expect(store.snapshot({...snapshot(other),customer:first.customer})).rejects.toThrow();await expect(db.query("INSERT INTO call_legs(session_id,role) VALUES($1,'customer')",[randomUUID()])).rejects.toThrow();});
});
describe("Phase 4 durable lifecycle and replay",()=>{
  it("persists ownership, diagnostics and idempotent events",async()=>{const id=randomUUID(),state=snapshot(id);await store.beginSession(id,"+919876543210");await store.snapshot(state,"callback.started","unique-event");await store.snapshot(state,"callback.started","unique-event");const detail=await store.detail(id);expect(detail.legs).toHaveLength(2);expect(detail.streams).toHaveLength(2);expect(detail.events).toHaveLength(1);expect((await store.history()).items[0].providerMode).toBe("offline");});
  it("rejects immutable call and request changes",async()=>{const id=randomUUID(),state=snapshot(id);await store.beginSession(id,"+919876543210");await store.snapshot(state);await expect(store.snapshot({...state,customer:{...state.customer,callUuid:"new-call"}})).rejects.toThrow("OWNERSHIP");await expect(store.snapshot({...state,customer:{...state.customer,requestUuid:"new-request"}})).rejects.toThrow("OWNERSHIP");});
  it("preserves retired streams and rejects reactivation",async()=>{const id=randomUUID(),state=snapshot(id);await store.beginSession(id,"+919876543210");await store.snapshot(state);const next={...state,customer:{...state.customer,streamId:"replacement-stream"}};await store.snapshot(next);await expect(store.snapshot(state)).rejects.toThrow("STREAM_OWNERSHIP");expect((await store.detail(id)).streams).toHaveLength(3);});
  it("claims callback nonce durably and refuses duplicate or altered reuse",async()=>{const id=randomUUID();await store.beginSession(id,"+919876543210");const digest="a".repeat(64),hash=await store.callbackClaim(id,"offline-nonce",digest);await store.callbackComplete(hash);const restarted=new ManagementStore(db);await expect(restarted.callbackClaim(id,"offline-nonce",digest)).rejects.toThrow("REPLAY");await expect(restarted.callbackClaim(id,"offline-nonce","b".repeat(64))).rejects.toThrow("REPLAY");expect(JSON.stringify(await db.query("SELECT * FROM callback_receipts"))).not.toContain("offline-nonce");});
  it("recovers interrupted sessions as closed without resurrecting sockets",async()=>{const id=randomUUID();await store.beginSession(id,"+919876543210");await store.snapshot(snapshot(id));const restarted=new ManagementStore(db);expect(await restarted.recover()).toBe(1);expect(await restarted.recover()).toBe(0);const detail=await restarted.detail(id);expect(detail.status).toBe("RECOVERY_CLOSED");expect(detail.legs.every(leg=>!leg.socketConnected && leg.status==="closed")).toBe(true);expect(detail.streams.every(stream=>stream.active===false)).toBe(true);});
  it("never reopens terminal sessions",async()=>{const id=randomUUID(),state=snapshot(id);await store.beginSession(id,"+919876543210");await store.snapshot({...state,state:"closed",closeReason:"staff-hangup"});await expect(store.snapshot(state)).rejects.toThrow("TERMINAL");});
  it("cleans expired offline records and related events without deleting active or legacy sessions",async()=>{const expired=randomUUID(),active=randomUUID();await store.beginSession(expired,"+919876543210");await store.snapshot({...snapshot(expired),state:"closed"});await db.query("UPDATE call_sessions SET ended_at=now()-interval '40 days' WHERE id=$1",[expired]);await store.beginSession(active,"+919876543210");await db.query("INSERT INTO call_sessions(call_id,status,provider_mode,ended_at) VALUES('legacy','COMPLETED','legacy',now()-interval '40 days')");expect(await store.cleanup(actor)).toEqual({deletedCalls:1});expect((await store.history()).total).toBe(2);expect(await db.query("SELECT * FROM call_legs WHERE session_id=$1",[expired])).toHaveLength(0);});
  it("filters history, search, counts and stable pagination",async()=>{for(let i=0;i<3;i++)await store.beginSession(randomUUID(),"+919876543210");const first=await store.history({page:1,limit:2}),second=await store.history({page:2,limit:2});expect(first.total).toBe(3);expect(first.items).toHaveLength(2);expect(second.items).toHaveLength(1);expect(first.items.some(row=>row.id===second.items[0].id)).toBe(false);expect((await store.history({search:String(second.items[0].id),mode:"offline"})).total).toBe(1);expect((await store.overview()).metrics.active).toBe(3);});
  it("does not retain audio, transcripts or tokens",async()=>{const id=randomUUID();await store.beginSession(id,"+919876543210");await store.snapshot(snapshot(id));expect(await db.query("SELECT * FROM call_transcripts")).toEqual([]);const stored=JSON.stringify(await store.detail(id));expect(stored).not.toMatch(/connectionToken|api.key|payload|transcript/i);});
});
describe("Phase 4 CRUD, API and authorization",()=>{
  it("normalizes employee phone with Tamil default",()=>{expect(employeeInput({name:"Employee",phone:"+91 (98765) 43210"})).toMatchObject({phone:"+919876543210",defaultLanguage:"ta",callingRole:"staff"});});
  it.each(["9876543210","+0123456789","+91<script>","+91abc"])("rejects invalid phone %s",phone=>{expect(()=>employeeInput({...employee,phone})).toThrow();});
  it("creates, updates, deletes employees with audited transactions",async()=>{const row=await store.saveEmployee(employee,actor);expect(row.phone).toBe("+919876543210");await store.saveEmployee({...employee,name:"Updated",enabled:false},actor,String(row.id));expect((await store.employees())[0]).toMatchObject({name:"Updated",enabled:false});await store.deleteEmployee(String(row.id),actor);expect(await store.employees()).toHaveLength(0);expect(await store.auditHistory()).toHaveLength(3);});
  it("enforces employee uniqueness",async()=>{await store.saveEmployee(employee,actor);await expect(store.saveEmployee(employee,actor)).rejects.toThrow();expect(await store.auditHistory()).toHaveLength(1);});
  it("creates, edits, searches and deletes glossary entries",async()=>{const row=await store.saveGlossary(glossary,actor);await store.saveGlossary({...glossary,sourceTerm:"GE Druck"},actor,String(row.id));expect(await store.glossary("Druck")).toHaveLength(1);await store.deleteGlossary(String(row.id),actor);expect(await store.glossary()).toHaveLength(0);});
  it.each(["NUNESENTITY1","<script>","{prompt}","unsafe\nterm"])("rejects unsafe glossary %s",sourceTerm=>{expect(()=>glossaryInput({...glossary,sourceTerm})).toThrow();});
  it("imports glossary atomically and bounds request size",async()=>{expect(await store.importGlossary([glossary,{...glossary,sourceTerm:"GST"}],actor)).toEqual({imported:2});await expect(store.importGlossary([glossary,{...glossary,sourceTerm:"<script>"}],actor)).rejects.toThrow();expect(await store.glossary()).toHaveLength(2);await expect(store.importGlossary(Array(51).fill(glossary),actor)).rejects.toThrow("LIMIT");});
  it("rolls back employee writes when audit persistence fails",async()=>{const failing:DatabaseConnection={...db,transaction:operation=>db.transaction(connection=>operation({...connection,query:async(text,args)=>{if(text.startsWith("INSERT INTO audit_logs"))throw new Error("AUDIT_DOWN");return connection.query(text,args);}}))};await expect(new ManagementStore(failing).saveEmployee(employee,actor)).rejects.toThrow("AUDIT_DOWN");expect(await store.employees()).toHaveLength(0);});
  it("rejects production gates or unsafe retention through settings",async()=>{await expect(store.saveSettings("translation",{audioIsolationVerified:true},actor)).rejects.toThrow();await expect(store.saveSettings("retention",{callDays:30,auditDays:90,retainAudio:true,retainTranscripts:false},actor)).rejects.toThrow();await store.saveSettings("retention",{callDays:10,auditDays:100,retainAudio:false,retainTranscripts:false},actor);expect((await store.settings()).retention).toMatchObject({callDays:10});});
  it("authenticates reads and rejects viewer mutation",async()=>{const app=await appFor();try{expect((await app.inject({url:"/management/employees"})).statusCode).toBe(401);expect((await app.inject({url:"/management/employees",headers:{authorization:"Bearer offline-viewer"}})).statusCode).toBe(200);expect((await app.inject({method:"POST",url:"/management/employees",headers:{authorization:"Bearer offline-viewer"},payload:employee})).statusCode).toBe(403);expect((await app.inject({method:"POST",url:"/management/employees",headers:{authorization:"Bearer offline-admin"},payload:employee})).statusCode).toBe(200);}finally{await app.close();}});
  it("returns truthful blocked diagnostics without secrets or provider calls",async()=>{const fetch=vi.spyOn(globalThis,"fetch");const app=await appFor();try{const response=await app.inject({url:"/management/diagnostics",headers:{authorization:"Bearer offline-admin"}});expect(response.json()).toMatchObject({database:"CONNECTED",productionReady:false,actualAudioIsolationVerified:false,productionTranslationAuthorized:false,providers:{plivo:{configured:true,connection:"NOT_VERIFIED"}}});expect(response.body).not.toMatch(/private-token|private-sarvam|configured-only/);expect(fetch).not.toHaveBeenCalled();}finally{fetch.mockRestore();await app.close();}});
  it("fails closed and sanitizes database outages",async()=>{const broken=new ManagementStore({...db,query:async()=>{throw new Error("postgresql://secret-password");}}),app=await appFor(broken);try{const response=await app.inject({url:"/management/employees",headers:{authorization:"Bearer offline-admin"}});expect(response.statusCode).toBe(503);expect(response.body).not.toContain("secret-password");expect((await app.inject({url:"/management/diagnostics",headers:{authorization:"Bearer offline-admin"}})).json()).toMatchObject({database:"UNAVAILABLE",persistence:"BLOCKED",productionReady:false});}finally{await app.close();}});
  it("bounds endpoint rate limits",async()=>{const app=await appFor();try{let response;for(let i=0;i<121;i++)response=await app.inject({url:"/management/identity",headers:{authorization:"Bearer offline-admin"}});expect(response!.statusCode).toBe(429);}finally{await app.close();}});
  it("checks pagination and cross-session detail IDs server side",async()=>{await expect(store.history({page:0})).rejects.toThrow("PAGINATION");await expect(store.history({limit:101})).rejects.toThrow("PAGINATION");await expect(store.detail("../other")).rejects.toThrow("ID");await expect(store.detail(randomUUID())).rejects.toThrow("NOT_FOUND");});
});
describe("Phase 4 dashboard sessions",()=>{
  it.each(["ADMIN","VIEWER"] as const)("signs %s without embedding the credential",role=>{const token=createSession(role,env);expect(verifySession(token,env)).toBe(role);expect(Buffer.from(token.split(".")[0],"base64url").toString()).not.toContain("offline-admin");});
  it("rejects tampering, expiration, missing secret and credential rotation",()=>{const token=createSession("ADMIN",env,1000);expect(verifySession(token+"x",env,1000)).toBeUndefined();expect(verifySession(token,env,1000+8*60*60*1000)).toBeUndefined();expect(verifySession(token,{...env,NUNES_ADMIN_PASSWORD:"changed"},1000)).toBeUndefined();expect(()=>createSession("ADMIN",{...env,AUTH_SECRET:"short"})).toThrow();});
});
